### ISSUE TITLE
Uncaught RangeError: The value of "offset" is out of range. It must be >= 0 and <= 84. Received 86

### ISSUE THREAD

**Issue by alexhien** [bus-stop/x-terminal#204] opened 2020-10-31 05:40 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro Education
**Thrown From**: [x-terminal](https://github.com/bus-stop/x-terminal) package 11.0.3

### Stack Trace

Uncaught RangeError: The value of "offset" is out of range. It must be >= 0 and <= 84. Received 86

```
At C:\Users\Alex\.atom\packages\x-terminal\node_modules\xterm-addon-ligatures\lib\xterm-addon-ligatures.js:9

RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 84. Received 86
    at boundsError (internal/buffer.js:73:9)
    at Buffer.readInt16BE (internal/buffer.js:493:5)
    at /packages/x-terminal/node_modules/font-finder/dist/tables/os2.js:56:29)
    at /packages/x-terminal/node_modules/font-finder/dist/parse.js:95:65
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

### Commands

```
     -2:38.6.0 command-palette:toggle (input.hidden-input)
  2x -2:22.4.0 build:select-active-target (input.hidden-input)
     -2:20.4.0 build:toggle-panel (input.hidden-input)
     -2:16.6.0 build:trigger (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -2:08.3.0 build:toggle-panel (input.hidden-input)
  2x -1:56.7.0 build:trigger (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:51.5.0 build:select-active-target (div.build.tool-panel.native-key-bindings)
     -1:46.1.0 core:confirm (input.hidden-input)
     -1:43.7.0 build:select-active-target (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:43.6.0 build:toggle-panel (input.hidden-input)
     -1:29.5.0 core:backspace (input.hidden-input)
     -1:29.2.0 core:confirm (input.hidden-input)
  2x -1:25.8.0 core:backspace (input.hidden-input)
     -1:23.8.0 core:confirm (input.hidden-input)
     -0:34.8.0 x-terminal:open (div.package-detail)
     -0:09.5.0 x-terminal:open-split-down (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.20.0 
build 0.70.0 
busy-signal 2.0.1 
drunken-php 0.2.4 
emmet 2.4.3 
nuclide-format-js 0.0.47 
script 3.26.0 
x-terminal 11.0.3 
```

**Comment by UziTech** [comment] 2020-10-31 05:56
What font are you using? it looks like the issue is in the [ligatures](https://github.com/xtermjs/xterm.js/tree/master/addons/xterm-addon-ligatures) addon.

**Comment by joogser** [comment] 2020-11-10 23:02
Please, help to fix, You have wrote this => it looks like the issue is in the [ligatures](https://github.com/xtermjs/xterm.js/tree/master/addons/xterm-addon-ligatures) addon

I don't very good to know how to use this hint in my case specifically for Atom, to fix this issue, take a look screen shot below:

![how-to-fix](https://user-images.githubusercontent.com/38474664/98743997-03d74800-23c2-11eb-80d8-420952767ebf.jpg)

**Comment by UziTech** [comment] 2020-11-10 23:21
what font are you using in atom?

**Comment by joogser** [comment] 2020-11-10 23:31
I use all settings by default, this is fresh installation, I'm beginner in Atom.
Font family I use is: **Menlo, Consolas, DejaVu Sans Mono, monospace**
![fonts-in-atom](https://user-images.githubusercontent.com/38474664/98746041-c1176f00-23c5-11eb-9cc1-fe5bc2f44c92.jpg)

**Comment by UziTech** [comment] 2020-11-11 05:06
Hmm, I can't reproduce this. I wonder if it has to do with how the font is installed on your system. The error stack looks like it is happening when x-terminal tries to load the font.

Can you try changing the font and seeing if it fixes it?

**Comment by joogser** [comment] 2020-11-11 11:01
I have uploaded video with diagnostic [here on youtube](https://youtu.be/d0gx5FX1064).

At this video I have made:
1) Removed previous Atom & Atom configuration directory.
2) Made new Atom install
3) Reproduced this issue with ligature.

This issue reproducing when I try write something on keyboard.
I did try to chose Arial & Verdana. MacOS High Sierra, fonts setup by defaults.

![issue](https://user-images.githubusercontent.com/38474664/98803643-21d69400-2426-11eb-8610-8dbce10e7f1c.png)

![2020-11-11_14-26-51](https://user-images.githubusercontent.com/38474664/98806422-3ddc3480-242a-11eb-8b11-942621d48492.png)

**Comment by UziTech** [comment] 2020-11-11 17:09
I created an issue on [xterm](https://github.com/xtermjs/xterm.js/issues/3174) and [font-finder](https://github.com/princjef/font-finder/issues/7).

It seems to be an issue with font-finder loading a font that is installed on your computer.

Could you do the following to help determine which font it is having problems with:

1. Open file: ~/.atom/packages/x-terminal/node_modules/font-finder/dist/index.js
2. Add console.log statment on line 34
   ![Screenshot 2020-11-11 110306](https://user-images.githubusercontent.com/97994/98841297-86392980-240d-11eb-9d2f-df3aaa3a3177.png)
3. Restart Atom.
4. Open Dev-Tools (<kbd>Alt</kbd> + <kbd>Cmd</kbd> + <kbd>I</kbd> on Mac)
5. Clear the console (<kbd>Cmd</kbd> + <kbd>K</kbd> or click the clear button):
   ![image](https://user-images.githubusercontent.com/97994/98841568-eb8d1a80-240d-11eb-8b4d-9454b97b86e8.png)
6. Try x-terminal again
7. copy output from console.log command here.

**Comment by joogser** [comment] 2020-11-11 18:19
Points **1**, **2** & **3** are done.

Which **Dev-Tools** exactly do you mean? According screen shot under **point 4**, it's look like a **Dev-Tool** in **Google Chrome**. I can't see dependencies between **Atom** & **Google Chrome**, how it may interact in this way of diagnostic?  For some logs in Chrome I have to open some page.

>Open **Dev-Tools** (Alt + Cmd + I on Mac) 
- by this combo I can open **Dev-Tools** in **Google Chrome**, in **Atom** I have open **X-Terminal**.

**Comment by UziTech** [comment] 2020-11-11 18:59
press <kbd>Alt</kbd> + <kbd>Cmd</kbd> + <kbd>I</kbd> in Atom. It will open chrome dev-tools in Atom. Atom runs on an older version of chrome.

**Comment by UziTech** [comment] 2020-11-11 19:06
or you can open it through the menu in Atom

View -> Developer -> Toggle Developer Tools

**Comment by joogser** [comment] 2020-11-11 19:09
![issue_diagnostic](https://user-images.githubusercontent.com/38474664/98853634-7b60b200-246a-11eb-871d-d069c0b5beb4.png)

**Comment by UziTech** [comment] 2020-11-11 19:15
try changing the log statement to `console.log(files, file, e.name);` and try again.

**Comment by joogser** [comment] 2020-11-11 19:22
![2020-11-11_22-18-52](https://user-images.githubusercontent.com/38474664/98854742-01312d00-246c-11eb-88b4-e60e353da73d.png)

![2020-11-11_22-22-00](https://user-images.githubusercontent.com/38474664/98855023-6c7aff00-246c-11eb-87f2-29f689f7162c.png)

**and full format (copy/paste) of last logs here:**

```
(1948) ["/Library/Fonts/Andale Mono.ttf", "/Library/Fonts/Apple Chancery.ttf", "/Library/Fonts/AppleGothic.ttf", "/Library/Fonts/AppleMyungjo.ttf", "/Library/Fonts/Arial Black.ttf", "/Library/Fonts/Arial Bold Italic.ttf", "/Library/Fonts/Arial Bold.ttf", "/Library/Fonts/Arial Italic.ttf", "/Library/Fonts/Arial Narrow Bold Italic.ttf", "/Library/Fonts/Arial Narrow Bold.ttf", "/Library/Fonts/Arial Narrow Italic.ttf", "/Library/Fonts/Arial Narrow.ttf", "/Library/Fonts/Arial Rounded Bold.ttf", "/Library/Fonts/Arial Unicode.ttf", "/Library/Fonts/Arial.ttf", "/Library/Fonts/Ayuthaya.ttf", "/Library/Fonts/BigCaslon.ttf", "/Library/Fonts/Bodoni 72 Smallcaps Book.ttf", "/Library/Fonts/Bodoni Ornaments.ttf", "/Library/Fonts/Bradley Hand Bold.ttf", "/Library/Fonts/Brush Script.ttf", "/Library/Fonts/Chalkduster.ttf", "/Library/Fonts/Comic Sans MS Bold.ttf", "/Library/Fonts/Comic Sans MS.ttf", "/Library/Fonts/Courier New Bold Italic.ttf", "/Library/Fonts/Courier New Bold.ttf", "/Library/Fonts/Courier New Italic.ttf", "/Library/Fonts/Courier New.ttf", "/Library/Fonts/DIN Alternate Bold.ttf", "/Library/Fonts/DIN Condensed Bold.ttf", "/Library/Fonts/Diwan Thuluth.ttf", "/Library/Fonts/Farisi.ttf", "/Library/Fonts/Georgia Bold Italic.ttf", "/Library/Fonts/Georgia Bold.ttf", "/Library/Fonts/Georgia Italic.ttf", "/Library/Fonts/Georgia.ttf", "/Library/Fonts/Gurmukhi.ttf", "/Library/Fonts/Herculanum.ttf", "/Library/Fonts/Hoefler Text Ornaments.ttf", "/Library/Fonts/Impact.ttf", "/Library/Fonts/Khmer Sangam MN.ttf", "/Library/Fonts/Kokonor.ttf", "/Library/Fonts/Krungthep.ttf", "/Library/Fonts/LG_Display11_Light.ttf", "/Library/Fonts/Lao Sangam MN.ttf", "/Library/Fonts/Luminari.ttf", "/Library/Fonts/Microsoft Sans Serif.ttf", "/Library/Fonts/Mishafi Gold.ttf", "/Library/Fonts/Mishafi.ttf", "/Library/Fonts/NISC18030.ttf", "/Library/Fonts/PlantagenetCherokee.ttf", "/Library/Fonts/STIXGeneral.otf", "/Library/Fonts/STIXGeneralBol.otf", "/Library/Fonts/STIXGeneralBolIta.otf", "/Library/Fonts/STIXGeneralItalic.otf", "/Library/Fonts/STIXIntDBol.otf", "/Library/Fonts/STIXIntDReg.otf", "/Library/Fonts/STIXIntSmBol.otf", "/Library/Fonts/STIXIntSmReg.otf", "/Library/Fonts/STIXIntUpBol.otf", "/Library/Fonts/STIXIntUpDBol.otf", "/Library/Fonts/STIXIntUpDReg.otf", "/Library/Fonts/STIXIntUpReg.otf", "/Library/Fonts/STIXIntUpSmBol.otf", "/Library/Fonts/STIXIntUpSmReg.otf", "/Library/Fonts/STIXNonUni.otf", "/Library/Fonts/STIXNonUniBol.otf", "/Library/Fonts/STIXNonUniBolIta.otf", "/Library/Fonts/STIXNonUniIta.otf", "/Library/Fonts/STIXSizFiveSymReg.otf", "/Library/Fonts/STIXSizFourSymBol.otf", "/Library/Fonts/STIXSizFourSymReg.otf", "/Library/Fonts/STIXSizOneSymBol.otf", "/Library/Fonts/STIXSizOneSymReg.otf", "/Library/Fonts/STIXSizThreeSymBol.otf", "/Library/Fonts/STIXSizThreeSymReg.otf", "/Library/Fonts/STIXSizTwoSymBol.otf", "/Library/Fonts/STIXSizTwoSymReg.otf", "/Library/Fonts/STIXVar.otf", "/Library/Fonts/STIXVarBol.otf", "/Library/Fonts/Sathu.ttf", "/Library/Fonts/Silom.ttf", "/Library/Fonts/Skia.ttf", "/Library/Fonts/SourceCodePro-Black.ttf", "/Library/Fonts/SourceCodePro-Bold.ttf", "/Library/Fonts/SourceCodePro-ExtraLight.ttf", "/Library/Fonts/SourceCodePro-Light.ttf", "/Library/Fonts/SourceCodePro-Regular.ttf", "/Library/Fonts/SourceCodePro-Semibold.ttf", "/Library/Fonts/Tahoma Bold.ttf", "/Library/Fonts/Tahoma.ttf", "/Library/Fonts/Times New Roman Bold Italic.ttf", "/Library/Fonts/Times New Roman Bold.ttf", "/Library/Fonts/Times New Roman Italic.ttf", "/Library/Fonts/Times New Roman.ttf", "/Library/Fonts/Trattatello.ttf", "/Library/Fonts/Trebuchet MS Bold Italic.ttf", "/Library/Fonts/Trebuchet MS Bold.ttf", "/Library/Fonts/Trebuchet MS Italic.ttf", "/Library/Fonts/Trebuchet MS.ttf", …] "/Users/mikhail.shitikov/Library/Fonts/ACADEBOL.TTF" "RangeError"
index.ts:99 (1948) ["/Library/Fonts/Andale Mono.ttf", "/Library/Fonts/Apple Chancery.ttf", "/Library/Fonts/AppleGothic.ttf", "/Library/Fonts/AppleMyungjo.ttf", "/Library/Fonts/Arial Black.ttf", "/Library/Fonts/Arial Bold Italic.ttf", "/Library/Fonts/Arial Bold.ttf", "/Library/Fonts/Arial Italic.ttf", "/Library/Fonts/Arial Narrow Bold Italic.ttf", "/Library/Fonts/Arial Narrow Bold.ttf", "/Library/Fonts/Arial Narrow Italic.ttf", "/Library/Fonts/Arial Narrow.ttf", "/Library/Fonts/Arial Rounded Bold.ttf", "/Library/Fonts/Arial Unicode.ttf", "/Library/Fonts/Arial.ttf", "/Library/Fonts/Ayuthaya.ttf", "/Library/Fonts/BigCaslon.ttf", "/Library/Fonts/Bodoni 72 Smallcaps Book.ttf", "/Library/Fonts/Bodoni Ornaments.ttf", "/Library/Fonts/Bradley Hand Bold.ttf", "/Library/Fonts/Brush Script.ttf", "/Library/Fonts/Chalkduster.ttf", "/Library/Fonts/Comic Sans MS Bold.ttf", "/Library/Fonts/Comic Sans MS.ttf", "/Library/Fonts/Courier New Bold Italic.ttf", "/Library/Fonts/Courier New Bold.ttf", "/Library/Fonts/Courier New Italic.ttf", "/Library/Fonts/Courier New.ttf", "/Library/Fonts/DIN Alternate Bold.ttf", "/Library/Fonts/DIN Condensed Bold.ttf", "/Library/Fonts/Diwan Thuluth.ttf", "/Library/Fonts/Farisi.ttf", "/Library/Fonts/Georgia Bold Italic.ttf", "/Library/Fonts/Georgia Bold.ttf", "/Library/Fonts/Georgia Italic.ttf", "/Library/Fonts/Georgia.ttf", "/Library/Fonts/Gurmukhi.ttf", "/Library/Fonts/Herculanum.ttf", "/Library/Fonts/Hoefler Text Ornaments.ttf", "/Library/Fonts/Impact.ttf", "/Library/Fonts/Khmer Sangam MN.ttf", "/Library/Fonts/Kokonor.ttf", "/Library/Fonts/Krungthep.ttf", "/Library/Fonts/LG_Display11_Light.ttf", "/Library/Fonts/Lao Sangam MN.ttf", "/Library/Fonts/Luminari.ttf", "/Library/Fonts/Microsoft Sans Serif.ttf", "/Library/Fonts/Mishafi Gold.ttf", "/Library/Fonts/Mishafi.ttf", "/Library/Fonts/NISC18030.ttf", "/Library/Fonts/PlantagenetCherokee.ttf", "/Library/Fonts/STIXGeneral.otf", "/Library/Fonts/STIXGeneralBol.otf", "/Library/Fonts/STIXGeneralBolIta.otf", "/Library/Fonts/STIXGeneralItalic.otf", "/Library/Fonts/STIXIntDBol.otf", "/Library/Fonts/STIXIntDReg.otf", "/Library/Fonts/STIXIntSmBol.otf", "/Library/Fonts/STIXIntSmReg.otf", "/Library/Fonts/STIXIntUpBol.otf", "/Library/Fonts/STIXIntUpDBol.otf", "/Library/Fonts/STIXIntUpDReg.otf", "/Library/Fonts/STIXIntUpReg.otf", "/Library/Fonts/STIXIntUpSmBol.otf", "/Library/Fonts/STIXIntUpSmReg.otf", "/Library/Fonts/STIXNonUni.otf", "/Library/Fonts/STIXNonUniBol.otf", "/Library/Fonts/STIXNonUniBolIta.otf", "/Library/Fonts/STIXNonUniIta.otf", "/Library/Fonts/STIXSizFiveSymReg.otf", "/Library/Fonts/STIXSizFourSymBol.otf", "/Library/Fonts/STIXSizFourSymReg.otf", "/Library/Fonts/STIXSizOneSymBol.otf", "/Library/Fonts/STIXSizOneSymReg.otf", "/Library/Fonts/STIXSizThreeSymBol.otf", "/Library/Fonts/STIXSizThreeSymReg.otf", "/Library/Fonts/STIXSizTwoSymBol.otf", "/Library/Fonts/STIXSizTwoSymReg.otf", "/Library/Fonts/STIXVar.otf", "/Library/Fonts/STIXVarBol.otf", "/Library/Fonts/Sathu.ttf", "/Library/Fonts/Silom.ttf", "/Library/Fonts/Skia.ttf", "/Library/Fonts/SourceCodePro-Black.ttf", "/Library/Fonts/SourceCodePro-Bold.ttf", "/Library/Fonts/SourceCodePro-ExtraLight.ttf", "/Library/Fonts/SourceCodePro-Light.ttf", "/Library/Fonts/SourceCodePro-Regular.ttf", "/Library/Fonts/SourceCodePro-Semibold.ttf", "/Library/Fonts/Tahoma Bold.ttf", "/Library/Fonts/Tahoma.ttf", "/Library/Fonts/Times New Roman Bold Italic.ttf", "/Library/Fonts/Times New Roman Bold.ttf", "/Library/Fonts/Times New Roman Italic.ttf", "/Library/Fonts/Times New Roman.ttf", "/Library/Fonts/Trattatello.ttf", "/Library/Fonts/Trebuchet MS Bold Italic.ttf", "/Library/Fonts/Trebuchet MS Bold.ttf", "/Library/Fonts/Trebuchet MS Italic.ttf", "/Library/Fonts/Trebuchet MS.ttf", …] "/Users/mikhail.shitikov/Library/Fonts/ACADEITA.TTF" "RangeError"
index.ts:99 (1948) ["/Library/Fonts/Andale Mono.ttf", "/Library/Fonts/Apple Chancery.ttf", "/Library/Fonts/AppleGothic.ttf", "/Library/Fonts/AppleMyungjo.ttf", "/Library/Fonts/Arial Black.ttf", "/Library/Fonts/Arial Bold Italic.ttf", "/Library/Fonts/Arial Bold.ttf", "/Library/Fonts/Arial Italic.ttf", "/Library/Fonts/Arial Narrow Bold Italic.ttf", "/Library/Fonts/Arial Narrow Bold.ttf", "/Library/Fonts/Arial Narrow Italic.ttf", "/Library/Fonts/Arial Narrow.ttf", "/Library/Fonts/Arial Rounded Bold.ttf", "/Library/Fonts/Arial Unicode.ttf", "/Library/Fonts/Arial.ttf", "/Library/Fonts/Ayuthaya.ttf", "/Library/Fonts/BigCaslon.ttf", "/Library/Fonts/Bodoni 72 Smallcaps Book.ttf", "/Library/Fonts/Bodoni Ornaments.ttf", "/Library/Fonts/Bradley Hand Bold.ttf", "/Library/Fonts/Brush Script.ttf", "/Library/Fonts/Chalkduster.ttf", "/Library/Fonts/Comic Sans MS Bold.ttf", "/Library/Fonts/Comic Sans MS.ttf", "/Library/Fonts/Courier New Bold Italic.ttf", "/Library/Fonts/Courier New Bold.ttf", "/Library/Fonts/Courier New Italic.ttf", "/Library/Fonts/Courier New.ttf", "/Library/Fonts/DIN Alternate Bold.ttf", "/Library/Fonts/DIN Condensed Bold.ttf", "/Library/Fonts/Diwan Thuluth.ttf", "/Library/Fonts/Farisi.ttf", "/Library/Fonts/Georgia Bold Italic.ttf", "/Library/Fonts/Georgia Bold.ttf", "/Library/Fonts/Georgia Italic.ttf", "/Library/Fonts/Georgia.ttf", "/Library/Fonts/Gurmukhi.ttf", "/Library/Fonts/Herculanum.ttf", "/Library/Fonts/Hoefler Text Ornaments.ttf", "/Library/Fonts/Impact.ttf", "/Library/Fonts/Khmer Sangam MN.ttf", "/Library/Fonts/Kokonor.ttf", "/Library/Fonts/Krungthep.ttf", "/Library/Fonts/LG_Display11_Light.ttf", "/Library/Fonts/Lao Sangam MN.ttf", "/Library/Fonts/Luminari.ttf", "/Library/Fonts/Microsoft Sans Serif.ttf", "/Library/Fonts/Mishafi Gold.ttf", "/Library/Fonts/Mishafi.ttf", "/Library/Fonts/NISC18030.ttf", "/Library/Fonts/PlantagenetCherokee.ttf", "/Library/Fonts/STIXGeneral.otf", "/Library/Fonts/STIXGeneralBol.otf", "/Library/Fonts/STIXGeneralBolIta.otf", "/Library/Fonts/STIXGeneralItalic.otf", "/Library/Fonts/STIXIntDBol.otf", "/Library/Fonts/STIXIntDReg.otf", "/Library/Fonts/STIXIntSmBol.otf", "/Library/Fonts/STIXIntSmReg.otf", "/Library/Fonts/STIXIntUpBol.otf", "/Library/Fonts/STIXIntUpDBol.otf", "/Library/Fonts/STIXIntUpDReg.otf", "/Library/Fonts/STIXIntUpReg.otf", "/Library/Fonts/STIXIntUpSmBol.otf", "/Library/Fonts/STIXIntUpSmReg.otf", "/Library/Fonts/STIXNonUni.otf", "/Library/Fonts/STIXNonUniBol.otf", "/Library/Fonts/STIXNonUniBolIta.otf", "/Library/Fonts/STIXNonUniIta.otf", "/Library/Fonts/STIXSizFiveSymReg.otf", "/Library/Fonts/STIXSizFourSymBol.otf", "/Library/Fonts/STIXSizFourSymReg.otf", "/Library/Fonts/STIXSizOneSymBol.otf", "/Library/Fonts/STIXSizOneSymReg.otf", "/Library/Fonts/STIXSizThreeSymBol.otf", "/Library/Fonts/STIXSizThreeSymReg.otf", "/Library/Fonts/STIXSizTwoSymBol.otf", "/Library/Fonts/STIXSizTwoSymReg.otf", "/Library/Fonts/STIXVar.otf", "/Library/Fonts/STIXVarBol.otf", "/Library/Fonts/Sathu.ttf", "/Library/Fonts/Silom.ttf", "/Library/Fonts/Skia.ttf", "/Library/Fonts/SourceCodePro-Black.ttf", "/Library/Fonts/SourceCodePro-Bold.ttf", "/Library/Fonts/SourceCodePro-ExtraLight.ttf", "/Library/Fonts/SourceCodePro-Light.ttf", "/Library/Fonts/SourceCodePro-Regular.ttf", "/Library/Fonts/SourceCodePro-Semibold.ttf", "/Library/Fonts/Tahoma Bold.ttf", "/Library/Fonts/Tahoma.ttf", "/Library/Fonts/Times New Roman Bold Italic.ttf", "/Library/Fonts/Times New Roman Bold.ttf", "/Library/Fonts/Times New Roman Italic.ttf", "/Library/Fonts/Times New Roman.ttf", "/Library/Fonts/Trattatello.ttf", "/Library/Fonts/Trebuchet MS Bold Italic.ttf", "/Library/Fonts/Trebuchet MS Bold.ttf", "/Library/Fonts/Trebuchet MS Italic.ttf", "/Library/Fonts/Trebuchet MS.ttf", …] "/Users/mikhail.shitikov/Library/Fonts/ACADEROM.TTF" "RangeError"
index.ts:99 (1948) ["/Library/Fonts/Andale Mono.ttf", "/Library/Fonts/Apple Chancery.ttf", "/Library/Fonts/AppleGothic.ttf", "/Library/Fonts/AppleMyungjo.ttf", "/Library/Fonts/Arial Black.ttf", "/Library/Fonts/Arial Bold Italic.ttf", "/Library/Fonts/Arial Bold.ttf", "/Library/Fonts/Arial Italic.ttf", "/Library/Fonts/Arial Narrow Bold Italic.ttf", "/Library/Fonts/Arial Narrow Bold.ttf", "/Library/Fonts/Arial Narrow Italic.ttf", "/Library/Fonts/Arial Narrow.ttf", "/Library/Fonts/Arial Rounded Bold.ttf", "/Library/Fonts/Arial Unicode.ttf", "/Library/Fonts/Arial.ttf", "/Library/Fonts/Ayuthaya.ttf", "/Library/Fonts/BigCaslon.ttf", "/Library/Fonts/Bodoni 72 Smallcaps Book.ttf", "/Library/Fonts/Bodoni Ornaments.ttf", "/Library/Fonts/Bradley Hand Bold.ttf", "/Library/Fonts/Brush Script.ttf", "/Library/Fonts/Chalkduster.ttf", "/Library/Fonts/Comic Sans MS Bold.ttf", "/Library/Fonts/Comic Sans MS.ttf", "/Library/Fonts/Courier New Bold Italic.ttf", "/Library/Fonts/Courier New Bold.ttf", "/Library/Fonts/Courier New Italic.ttf", "/Library/Fonts/Courier New.ttf", "/Library/Fonts/DIN Alternate Bold.ttf", "/Library/Fonts/DIN Condensed Bold.ttf", "/Library/Fonts/Diwan Thuluth.ttf", "/Library/Fonts/Farisi.ttf", "/Library/Fonts/Georgia Bold Italic.ttf", "/Library/Fonts/Georgia Bold.ttf", "/Library/Fonts/Georgia Italic.ttf", "/Library/Fonts/Georgia.ttf", "/Library/Fonts/Gurmukhi.ttf", "/Library/Fonts/Herculanum.ttf", "/Library/Fonts/Hoefler Text Ornaments.ttf", "/Library/Fonts/Impact.ttf", "/Library/Fonts/Khmer Sangam MN.ttf", "/Library/Fonts/Kokonor.ttf", "/Library/Fonts/Krungthep.ttf", "/Library/Fonts/LG_Display11_Light.ttf", "/Library/Fonts/Lao Sangam MN.ttf", "/Library/Fonts/Luminari.ttf", "/Library/Fonts/Microsoft Sans Serif.ttf", "/Library/Fonts/Mishafi Gold.ttf", "/Library/Fonts/Mishafi.ttf", "/Library/Fonts/NISC18030.ttf", "/Library/Fonts/PlantagenetCherokee.ttf", "/Library/Fonts/STIXGeneral.otf", "/Library/Fonts/STIXGeneralBol.otf", "/Library/Fonts/STIXGeneralBolIta.otf", "/Library/Fonts/STIXGeneralItalic.otf", "/Library/Fonts/STIXIntDBol.otf", "/Library/Fonts/STIXIntDReg.otf", "/Library/Fonts/STIXIntSmBol.otf", "/Library/Fonts/STIXIntSmReg.otf", "/Library/Fonts/STIXIntUpBol.otf", "/Library/Fonts/STIXIntUpDBol.otf", "/Library/Fonts/STIXIntUpDReg.otf", "/Library/Fonts/STIXIntUpReg.otf", "/Library/Fonts/STIXIntUpSmBol.otf", "/Library/Fonts/STIXIntUpSmReg.otf", "/Library/Fonts/STIXNonUni.otf", "/Library/Fonts/STIXNonUniBol.otf", "/Library/Fonts/STIXNonUniBolIta.otf", "/Library/Fonts/STIXNonUniIta.otf", "/Library/Fonts/STIXSizFiveSymReg.otf", "/Library/Fonts/STIXSizFourSymBol.otf", "/Library/Fonts/STIXSizFourSymReg.otf", "/Library/Fonts/STIXSizOneSymBol.otf", "/Library/Fonts/STIXSizOneSymReg.otf", "/Library/Fonts/STIXSizThreeSymBol.otf", "/Library/Fonts/STIXSizThreeSymReg.otf", "/Library/Fonts/STIXSizTwoSymBol.otf", "/Library/Fonts/STIXSizTwoSymReg.otf", "/Library/Fonts/STIXVar.otf", "/Library/Fonts/STIXVarBol.otf", "/Library/Fonts/Sathu.ttf", "/Library/Fonts/Silom.ttf", "/Library/Fonts/Skia.ttf", "/Library/Fonts/SourceCodePro-Black.ttf", "/Library/Fonts/SourceCodePro-Bold.ttf", "/Library/Fonts/SourceCodePro-ExtraLight.ttf", "/Library/Fonts/SourceCodePro-Light.ttf", "/Library/Fonts/SourceCodePro-Regular.ttf", "/Library/Fonts/SourceCodePro-Semibold.ttf", "/Library/Fonts/Tahoma Bold.ttf", "/Library/Fonts/Tahoma.ttf", "/Library/Fonts/Times New Roman Bold Italic.ttf", "/Library/Fonts/Times New Roman Bold.ttf", "/Library/Fonts/Times New Roman Italic.ttf", "/Library/Fonts/Times New Roman.ttf", "/Library/Fonts/Trattatello.ttf", "/Library/Fonts/Trebuchet MS Bold Italic.ttf", "/Library/Fonts/Trebuchet MS Bold.ttf", "/Library/Fonts/Trebuchet MS Italic.ttf", "/Library/Fonts/Trebuchet MS.ttf", …] "/Users/mikhail.shitikov/Library/Fonts/CRR35__E.TTF" "RangeError"
2index.ts:80 Uncaught RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 373. Received 375
    at boundsError (internal/buffer.js:73)
    at Buffer.readUInt16BE (internal/buffer.js:319)
    at Object.parseNameTable [as parse] (name.ts:525)
    at parse.ts:112
    at processTicksAndRejections (internal/process/task_queues.js:89)
NodeError @ internal/errors.js:194
boundsError @ internal/buffer.js:73
readUInt16BE @ internal/buffer.js:319
parseNameTable @ name.ts:525
(anonymous) @ parse.ts:112
processTicksAndRejections @ internal/process/task_queues.js:89
requestAnimationFrame (async)
e.refresh @ RenderDebouncer.ts:47
t.refreshRows @ RenderService.ts:112
t.refresh @ Terminal.ts:820
(anonymous) @ Terminal.ts:149
e.fire @ EventEmitter.ts:67
t.parse @ InputHandler.ts:500
(anonymous) @ CoreTerminal.ts:64
e._innerWrite @ WriteBuffer.ts:98
(anonymous) @ WriteBuffer.ts:80
setTimeout (async)
e.write @ WriteBuffer.ts:79
t.write @ CoreTerminal.ts:137
e.write @ Terminal.ts:169
(anonymous) @ element.js? [sm]:596
emit @ events.js:205
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
index.ts:80 Uncaught RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 373. Received 375
    at boundsError (internal/buffer.js:73)
    at Buffer.readUInt16BE (internal/buffer.js:319)
    at Object.parseNameTable [as parse] (name.ts:525)
    at parse.ts:112
    at processTicksAndRejections (internal/process/task_queues.js:89)
```

**Comment by UziTech** [comment] 2020-11-11 19:32
Thanks that seems like it should help figure out what the issue is with loading certain fonts.

If you comment out the line `throw e;` does it stop the errors?

![image](https://user-images.githubusercontent.com/97994/98855866-58aaab00-2422-11eb-892f-6ed73e5272ef.png)

**Comment by joogser** [comment] 2020-11-11 19:38
Yes, after this comment out works fine. Thanks.

**Comment by joogser** [comment] 2020-11-11 19:41
By the way, it would be great realise SSH terminal, like FTP-Remote-Edit plugin or another SSH client for work with CLI.
I would like edit docs and use bash terminal via Atom in two separated window.
In this case with X-terminal I need make and write ssh 10.1.1.1... lalala to make remote connection to server. Right now it's uncomfortable.

**Comment by UziTech** [comment] 2020-11-11 19:52
If you want to send commands to the terminal with a button click or from the command palette you can install the [terminal commands](https://atom.io/packages/terminal-commands) package

**Comment by UziTech** [comment] 2020-12-02 16:23
This should be fixed by https://github.com/xtermjs/xterm.js/pull/3188

**Closed as completed** 2021-01-19 16:45 UTC
Labels: bug report :bug:, xterm-bug :bug:, released
