### ISSUE TITLE
Uncaught TypeError: Cannot read property 'copyCellsFrom' of undefined

### ISSUE THREAD

**Issue by ywanHK** [bus-stop/x-terminal#145] opened 2020-08-24 19:41 UTC
[Enter steps to reproduce:]

1. open terminal in the right dock
2. make the dock as narrow as possible
3. clear the console by typing "clear" (MSYS2 command)
4. resize the dock (first making it wider and then narrower)

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Windows 10
**Thrown From**: [x-terminal](https://github.com/bus-stop/x-terminal) package 9.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'copyCellsFrom' of undefined

```
At C:\Users\Lenovo\.atom\packages\x-terminal\node_modules\xterm\lib\xterm.js:1

TypeError: Cannot read property 'copyCellsFrom' of undefined
    at e._reflowSmaller (/packages/x-terminal/node_modules/xterm/lib/xterm.js:1:269077)
    at e._reflow (/packages/x-terminal/node_modules/xterm/lib/xterm.js:1:267570)
    at e.resize (/packages/x-terminal/node_modules/xterm/lib/xterm.js:1:267189)
    at t.resize (/packages/x-terminal/node_modules/xterm/lib/xterm.js:1:263460)
    at r.resize (/packages/x-terminal/node_modules/xterm/lib/xterm.js:1:261400)
    at t.resize (/packages/x-terminal/node_modules/xterm/lib/xterm.js:1:253139)
    at t.resize (/packages/x-terminal/node_modules/xterm/lib/xterm.js:1:127968)
    at e.resize (/packages/x-terminal/node_modules/xterm/lib/xterm.js:1:98529)
    at e.fit (/packages/x-terminal/node_modules/xterm-addon-fit/lib/xterm-addon-fit.js:1:1723)
    at HTMLElement.refitTerminal (/packages/x-terminal/src/element.js:692:18)
    at /packages/x-terminal/src/element.js:95:10)
```

### Commands

```
  2x -0:26.5.0 x-terminal:open (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
x-terminal 9.1.1 
```

**Comment by UziTech** [comment] 2020-08-24 20:48
![x-terminal](https://user-images.githubusercontent.com/97994/91094858-04f9a400-e621-11ea-873a-3cb07842162b.gif)

I am not able to reproduce this. Can you show the error happening. It seems this is an issue with xterm trying to resize when it shouldn't but I can't seem to make this happen.

**Comment by the-j0k3r** [comment] 2020-08-25 07:18
In my experience the error is garbage and meaningless, If I were you, I would remove x-terminal by hand from `%userprofile%\.atom\packages` and reinstall it via command line.

Next time you have upgrades for x-terminal, make sure that you have x-terminal not in use (check the task manager processes and kill all terminals, powershell, bash etc)), because if x-terminal is active, the upgrade is botched by APM and you likely will see this error and other errors as a consequence if not actually a totally broken install which errors out saying [it failed to load  the package](https://github.com/bus-stop/x-terminal/issues/76) (the install dir will be half empty or mostly empty).

In any case, unrelated a bit, electron 6.x Atom will be making its way out the doors soon which should take care of a few electron bugs that cause further instability.

I also cannot duplicate this.

![generic](https://user-images.githubusercontent.com/31389848/91145100-3e7bef00-e6b5-11ea-8bb2-a5bdf4e5c643.gif)

**Comment by the-j0k3r** [comment] 2020-08-25 08:02
on another unrelated note, I dislike the fact that Atom stack traces such as this prompt users to open an issue that doesn't contain half of the needed information, like OS version/type for one. It be great if packages could bypass this.

**Comment by ywanHK** [comment] 2020-08-25 11:09
It seems that WebGL Renderer has a bug in it

If I disable it, the error doesn't show anymore

**Comment by the-j0k3r** [comment] 2020-08-25 13:40
AH webgl, have it disabled will try with it enabled.

However my previous reply applies, stacktrace errors like this are a dime a dozen and none point to the right direction.

**Comment by UziTech** [comment] 2020-08-25 13:56
I have WebGL enabled in my gif. The error looks like it is coming from https://github.com/xtermjs/xterm.js/blob/106d74caa270bcee61e87895b3c2a6536b04a803/src/common/buffer/Buffer.ts#L370 after x-terminal calls `refitTerminal`

**Comment by UziTech** [comment] 2020-08-25 14:00
WebGL is still listed as an [experimental addon](https://github.com/xtermjs/xterm.js/tree/master/addons/xterm-addon-webgl#xterm-addon-webgl). Maybe we should put a note in the settings about this?

**Comment by the-j0k3r** [comment] 2020-08-25 14:25
Something in https://github.com/bus-stop/x-terminal/blob/71fb8ab1e4743ec94adbdf9a6d30d1495ac75d6b/src/config.js#L258

`Enable the experimental WebGL-based renderer using the xterm.js [WebGL addon](https://github.com/xtermjs/xterm.js/tree/master/addons/xterm-addon-webgl)`

Just added **experimental** word, its already disabled by default so tbh thers not much else to add here, ppl generally dont read docs or what settings say, so adding more verbose description wont do much for anything.

**Comment by UziTech** [comment] 2020-08-25 14:40
I created #149 to add the note

**Comment by UziTech** [comment] 2020-10-07 15:12
I'm going to close this as it is not reproducible and disabling WebGL seemed to fix it.

**Closed as completed by UziTech** 2020-10-07 15:12 UTC
Labels: bug report :bug:, unable to duplicate !!
