### ISSUE TITLE
Uncaught RangeError: The value of "offset" is out of range. It must be >= 0 and <= 1750. Received...

### ISSUE THREAD

**Issue by softwarecreations** [bus-stop/x-terminal#181] opened 2020-10-09 14:21 UTC
I just opened the x-terminal (which I used without issue yesterday on the previous version) and it crashed.
It's unusable.

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Debian GNU/Linux
**Thrown From**: [x-terminal](https://github.com/bus-stop/x-terminal) package 11.0.2

### Stack Trace

Uncaught RangeError: The value of "offset" is out of range. It must be >= 0 and <= 1750. Received 1752

```
At ~/.atom/packages/x-terminal/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js:9

RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 1750. Received 1752
    at boundsError (internal/buffer.js:58:9)
    at Buffer.readUInt16BE (internal/buffer.js:228:5)
    at /packages/x-terminal/node_modules/font-finder/dist/tables/name.js:488:29)
    at /packages/x-terminal/node_modules/font-finder/dist/parse.js:94:51
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

### Commands

```
     -9:43 core:delete (input.hidden-input)
     -9:42.4.0 core:save (input.hidden-input)
     -9:27.8.0 core:delete (input.hidden-input)
     -9:27.1.0 core:save (input.hidden-input)
     -0:39.6.0 x-terminal:open (atom-pane.pane.active)
```

**Comment by UziTech** [comment] 2020-10-09 15:33
Looks like the error is coming from the ligatures addon. What font are you using?

**Comment by softwarecreations** [comment] 2020-10-13 15:37
@UziTech interestingly, every time I've restarted Atom since then, the bug has not re-occurred.
In Preferences > Editor, I do not have any font family specified. When I hover over the field it says `Default: Menlo, Consolas, DejaVu Sans Mono, monospace`

**Comment by UziTech** [comment] 2020-10-13 17:20
ok I'm going to close this issue as it is not reproducible. If it happens again feel free to reopen it and try to give as much detail as you can.

**Closed as completed by UziTech** 2020-10-13 17:20 UTC
Labels: bug report :bug:, xterm-bug :bug:, unable to duplicate !!

**Comment by softwarecreations** [comment] 2020-11-15 14:10
This error has occurred another one or 2 times since I posted this issue.
The numbers involved relating to the range within the error message seem to vary.

A few minutes ago it occurred again, I closed and reopened atom a few times, but the error persisted.
Then I removed the project dirs, then closed and re-opened atom... then it was fine :/

**Comment by UziTech** [comment] 2020-11-15 16:07
Check #204 for a temporary solution. This is a bug in the ligatures addon for xterm.

**Comment by softwarecreations** [comment] 2020-11-26 12:05
Thanks will have a look
Latest error:
```
Uncaught RangeError: The value of "offset" is out of range. It must be >= 0 and <= 1818. Received 1820
RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 1818. Received 1820
    at boundsError (internal/buffer.js:73:9)
    at Buffer.readUInt16BE (internal/buffer.js:319:5)
    at Object.parseNameTable [as parse] (~/.atom/packages/x-terminal/node_modules/font-finder/dist/tables/name.js:486:33)
    at ~/.atom/packages/x-terminal/node_modules/font-finder/dist/parse.js:94:51
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```
