### ISSUE TITLE
Uncaught RangeError: The value of "offset" is out of range. It must be >= 0 and <= 385. Received 387

### ISSUE THREAD

**Issue by joogser** [bus-stop/x-terminal#211] opened 2020-11-10 21:41 UTC
My steps

1. I did install Atom and X-Terminal plugin.
2. I did open Packeges => X-Terminal => Open new Terminal and I've got this error:

![issue](https://user-images.githubusercontent.com/38474664/98737609-7989e680-23b7-11eb-9f10-ffebf85e8215.png)

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.13.6
**Thrown From**: [x-terminal](https://github.com/bus-stop/x-terminal) package 11.0.4

### Stack Trace

Uncaught RangeError: The value of "offset" is out of range. It must be >= 0 and <= 385. Received 387

```
At /Users/nickname/.atom/packages/x-terminal/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js:9

RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 385. Received 387
    at boundsError (internal/buffer.js:73:9)
    at Buffer.readUInt16BE (internal/buffer.js:319:5)
    at /packages/x-terminal/node_modules/font-finder/dist/tables/name.js:501:37)
    at /packages/x-terminal/node_modules/font-finder/dist/parse.js:94:51
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

### Commands

```
     -4:45.4.0 core:backspace (input.hidden-input)
     -0:25 x-terminal:open (div.package-detail)
```

### Non-Core Packages

```
ftp-remote-edit-plus 1.2.0 
platformio-ide-terminal 2.10.0 
x-terminal 11.0.4 
```

**Comment by UziTech** [comment] 2020-11-10 22:02
duplicate of #204 please answer the questions on that issue for more help.

**Closed as completed by UziTech** 2020-11-10 22:02 UTC
