### ISSUE TITLE
[FR]  Add a status-bar/tool-bar button for showing/hiding the terminal

### ISSUE THREAD

**Issue by aminya** [bus-stop/x-terminal#127] opened 2020-07-26 22:17 UTC
I wish there was a button (status-bar or tool-bar) that I could press to show the already open terminal. I tend to do that a lot when I am coding. I do not want the terminal to be open all the time.

Now it is annoying every time I open and close the bottom dock, the linter is shown instead of the terminal.

![terminal-dock](https://user-images.githubusercontent.com/16418197/88490788-aed30b80-cf63-11ea-8eda-ecedad8516b9.gif)

**Comment by UziTech** [comment] 2020-07-27 04:04
duplicate of #9

**Closed as completed by UziTech** 2020-07-27 04:04 UTC
Labels: duplicate :sheep::sheep:
