### ISSUE TITLE
Uncaught RangeError: The value of "offset" is out of range. It must be >= 0 and <= 2180. Received...

### ISSUE THREAD

**Issue by ajozz13** [bus-stop/x-terminal#206] opened 2020-11-06 19:06 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 18.04.5
**Thrown From**: [x-terminal](https://github.com/bus-stop/x-terminal) package 11.0.4

### Stack Trace

Uncaught RangeError: The value of "offset" is out of range. It must be >= 0 and <= 2180. Received 2182

```
At /home/aochoa/.atom/packages/x-terminal/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js:9

RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 2180. Received 2182
    at boundsError (internal/buffer.js:73:9)
    at Buffer.readUInt16BE (internal/buffer.js:319:5)
    at /packages/x-terminal/node_modules/font-finder/dist/tables/name.js:487:33)
    at /packages/x-terminal/node_modules/font-finder/dist/parse.js:94:51
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

### Commands

```
```

### Non-Core Packages

```
atom-minify 0.8.0 
language-julia 0.20.0 
x-terminal 11.0.4 
```

**Comment by UziTech** [comment] 2020-11-06 19:22
duplicate of #204

**Closed as completed by UziTech** 2020-11-06 19:22 UTC
