### ISSUE TITLE
[BR] Terminal text selection background/font color issues

### ISSUE THREAD

**Issue by the-j0k3r** [bus-stop/x-terminal#7] opened 2020-02-25 11:21 UTC
![generic](https://user-images.githubusercontent.com/31389848/75242950-54256000-57c9-11ea-9bd7-f4b4aa53c475.gif)

One dark terminal theme

**Comment by the-j0k3r** [comment] 2020-02-25 11:43
Essentially all themes including custom is similar to above =(

**Comment by UziTech** [comment] 2020-02-25 16:10
looks like it might be an issue in xterm. It doesn't seem to happen if webgl is enabled.

webgl:
![image](https://user-images.githubusercontent.com/97994/75265669-d9ebe000-57b6-11ea-92ee-0277138170fc.png)

non-webgl:
![image](https://user-images.githubusercontent.com/97994/75265721-ea9c5600-57b6-11ea-8514-0b964fe75cea.png)

**Comment by the-j0k3r** [comment] 2020-02-25 16:22
The themes (some) have a selection foreground commented out, I wonder if setting that will be best

**Comment by UziTech** [comment] 2020-02-25 16:45
x-term doesn't have a selection foreground setting which is why those are commented out. [docs](https://xtermjs.org/docs/api/terminal/interfaces/itheme/)

the selection can be transparent, unfortunately the chrome color picker has no way to indicate that you want the color to be transparent.

We might need a different way to choose the colors or at least choose the transparency.

**Comment by the-j0k3r** [comment] 2020-02-25 16:49
If it supports `rgba(153,153,153,.5) ` instead of `#999999` that has alpha of 50%

**Comment by the-j0k3r** [comment] 2020-02-25 16:50
No problem I can fix that, famous last words if it supports `rgba(153,153,153,.5) ` instead of `#999999` that has alpha of 50%

**Comment by the-j0k3r** [comment] 2020-02-25 16:50
If it supports `rgba(153,153,153,.5) ` instead of `#999999` that has alpha of 50%

**Comment by UziTech** [comment] 2020-02-25 20:53
This is confirmed to be an issue in xterm https://github.com/xtermjs/xterm.js/issues/2737

**Comment by UziTech** [comment] 2020-02-25 21:55
https://github.com/bus-stop/x-terminal/pull/2 should be a temporary fix for this

**Comment by the-j0k3r** [comment] 2020-02-27 12:02
I can now confirm #2 fixed this.

Its now possible to see what one has selected.

![generic](https://user-images.githubusercontent.com/31389848/75443079-f6c41700-5960-11ea-8782-8324dcbddad8.gif)

I'm personally more partial to tweak the opacity for less rather than more though.

It would be nice to be able to define foreground color, but since this isnt supported by xterm.js I wonder why themes cant be styled via CSS, because CSS allows this.

**Comment by UziTech** [comment] 2020-06-11 21:03
This was fixed in xterm v4.7.0 https://github.com/xtermjs/xterm.js/pull/2952 and should be working once #94 is merged.

**Closed as completed** 2020-06-11 21:05 UTC
Labels: released :postbox:, xterm-bug :bug:, external :outbox_tray:

**Comment by softwarecreations** [comment] 2020-10-19 08:20
@the-j0k3r @UziTech
I find it hard to see which text is selected and which text is not because there's not much contrast between the Background Color of the terminal and the Selection Background Color. I'm using theme Custom, which looks identical to Atom Dark (my whole Atom is dark)

I tried to adjust the opacity of Selection Background Color in x-terminal 11.0.1, but it seems to only take a colour in the format `#abcdef` (where the letters can be any hex number of course). It doesn't take `#abc` which isn't really an issue, but I can't for example set `#abcdefgh` where gh is opacity and cannot set the Selection Background Color to `rgba(88,88,88,1)` or any rgba value.

But I've worked around this issue by simply setting Selection Background Color to `#00ff00` and for me, that's very readable and get's the job done. Just thought I'd mention this.

**Comment by the-j0k3r** [comment] 2020-10-19 09:00
>I find it hard to see which text is selected and which text is not because there's not much contrast between the Background Color of the terminal and the Selection Background Color. I'm using theme Custom, which looks identical to Atom Dark (my whole Atom is dark)

Why not use the actual theme that already matches the One Dark thats default with Atom?
Also, custom means you have to choose different enough colors, if the default colors for custom has an issue we can fix it.

>but I can't for example set #abcdefgh where gh is opacity and cannot set the Selection Background Color to rgba(88,88,88,1) or any rgba value.

Always try to use rgb/rgba values, they work well on my previous tests, idk why it doesnt work with similar hex short or transparency values, havent tried it. **But that seems x-term issue/limitation to me**. Like I said havent tested/tried such colors.

Also try with webgl on and off, it makes huge difference in terms of color display, I find webgl distorts the display of selection bg colors on my tests.

> Just thought I'd mention this.

Didnt you want to get some work done? =)

**Comment by softwarecreations** [comment] 2020-10-20 05:31
The specific theme doesn't matter really.
I can't use webgl on this device.

> Didnt you want to get some work done? =)

Yes, need to be able to see which text I'm selecting in the terminal to do that :)

It's all good. The workaround works.
