### ISSUE TITLE
Uncaught RangeError: The value of "offset" is out of range. It must be >= 0 and <= 7981. Received...

### ISSUE THREAD

**Issue by abrahamafriyie** [bus-stop/x-terminal#220] opened 2020-11-19 08:27 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 18.04.5
**Thrown From**: [x-terminal](https://github.com/bus-stop/x-terminal) package 11.0.4

### Stack Trace

Uncaught RangeError: The value of "offset" is out of range. It must be >= 0 and <= 7981. Received 7982

```
At /home/cumucore/.atom/packages/x-terminal/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js:9

RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 7981. Received 7982
    at boundsError (internal/buffer.js:73:9)
    at Buffer.readUInt16BE (internal/buffer.js:319:5)
    at /packages/x-terminal/node_modules/font-finder/dist/tables/name.js:490:33)
    at /packages/x-terminal/node_modules/font-finder/dist/parse.js:94:51
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

### Commands

```
  2x -0:39.6.0 x-terminal:open-split-bottom-dock (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-alignment 0.13.0 
atom-beautify 0.33.4 
atom-file-icons 0.7.1 
atom-ide-ui 0.13.0 
atom-live-server 2.3.0 
atom-terminal 0.8.0 
autocomplete-modules 2.3.0 
autocomplete-paths 2.12.6 
emmet 2.4.3 
file-icons 2.1.44 
file-watcher 2.0.0 
formatter-tidy 1.0.1 
git-plus 8.7.1 
go-debug 1.7.0 
go-imports 0.2.0 
go-plus 6.1.0 
go-signature-statusbar 1.2.3 
gotests 0.4.1 
highlight-colors 0.9.0 
highlight-selected 0.17.0 
iv-terminal 1.3.1 
json-to-go-struct 0.0.5 
kite 0.196.0 
language-icon 0.1.1 
pigments 0.40.6 
terminal-plus 0.14.5 
tokamak-terminal 10.0.1 
vk-terminal 3.0.1 
x-terminal 11.0.4 
xml-formatter 0.13.0 
```

**Comment by UziTech** [comment] 2020-11-20 23:21
duplicate of #204

**Closed as completed by UziTech** 2020-11-20 23:21 UTC
